### PR TITLE
[WIP] Update tr1 include to make compatible with OSX clang >= 13

### PR DESCRIPTION
**Pull request by ymontmarin**

### CODE REVIEW

**Comment by ymontmarin** [comment]
I added the [WIP] because maybe you still have some process using c++<11. Anyway,, clang>=13 does not support natively tr1 and from c++11, unordered_map and unordered_set are in std.

**Review by nim65s — APPROVED** [review]
We enforce C++ >= 14 here, so this can be merged. Thanks !

**Comment by ymontmarin** [comment]
@nim65s I think it is ready to merge

**Comment by nim65s** [comment]
CI is failing for boost 1.74, which is fixed in devel. Could you rebase this PR onto the current devel ?

**Comment by ymontmarin** [comment]
@nim65s It should be ok now

**Pull request merged**
