### PR TITLE
ManipulationPlanner calls the problem PathValidation instead of the e…

### PR DESCRIPTION
**Pull request by jmirabel**
…dge one.

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
I do not understand. For waypoint edges, the "PathValidation" of the problem will not use the correct "RelativeMotion" matrices and the correct security margins, right ?

**Comment by jmirabel** [comment]
If the PathValidation is of type GraphPathValidation, it will.

**Comment by florent-lamiraux** [comment]
Understood.
Have you had the opportunity to test ?

**Comment by jmirabel** [comment]
Yes, on the Tiago case. I sent you a message on riot.

**Pull request merged**
