### PR TITLE
Allow to solve constraints level by level.

### PR DESCRIPTION
**Pull request by florent-lamiraux**
Related to https://github.com/humanoid-path-planner/hpp-constraints/pull/154

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by florent-lamiraux** [comment]
> Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you can change the base branch of this PR to devel (No need to close it for that). Best, a bot.

Yes, I know, it was a mistake. By the way, how did you notice from your closet without connection to the internet ?

**Comment by nim65s** [comment]
>  By the way, how did you notice from your closet without connection to the internet ?

it ascended, and is no longer bound to its material body :)

**Comment by florent-lamiraux** [comment]
Requires https://github.com/humanoid-path-planner/hpp-constraints/pull/155.

**Pull request merged**
